
version: "3.9"
services:
  web:
    build: 
      context: .
      dockerfile: docker/Dockerfile.web

    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

    ports:
      - "80:80"
      - "443:443"

    environment:
      SSL_ON: true

    container_name: beehive-web
    tty: true
    
    volumes:
      - ./app:/bees/app
      - /etc/letsencrypt/live/bees.eugene-dev.com/fullchain.pem:/var/ssl/cert.pem
      - /etc/letsencrypt/live/bees.eugene-dev.com/privkey.pem:/var/ssl/key.pem

  
  db:
    image: postgres:15.1-alpine
    restart: always
    
    environment:
      POSTGRES_PASSWORD: pg-admin

    ports:
      - '6432:5432'

    container_name: beehive-db
    tty: true

    volumes: 
      - /var/mysql/bees:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

