version: "3.9"
services:
  web:
    build: 
      context: .
      dockerfile: docker/Dockerfile.web

    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

    ports:
      - "80:80"
      - "443:443"

    container_name: beehive-web
    tty: true
    
    volumes:
      - ./app:/bees/app

    

