FROM ubuntu:20.04

SHELL ["/bin/bash", "-c"]

WORKDIR /bees

COPY . .

RUN apt-get update
RUN apt-get install -y apt-utils
RUN apt-get install -y curl 
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
RUN apt-get install -y nodejs

RUN npm install
RUN npm install -g ts-node

CMD ["sh", "-c", "ts-node app/app.ts" ]